"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useJobStream } from "@/hooks/useJobStream";
import {
  getJob,
  getResearchBrief,
  getScript,
  getIdeas,
  getScore,
  ScoreResponse,
} from "@/lib/api";
import { IdeaPicker } from "./IdeaPicker";
import { SelfScorePanel } from "./SelfScorePanel";
import { JobActions } from "@/components/JobActions";
import { MediaPreview } from "@/components/MediaPreview";
import { StageProgress } from "@/components/StageProgress";
import { StatusPill } from "@/components/StatusPill";
import { ResearchBriefPanel } from "@/components/ResearchBriefPanel";
import { ScriptPanel } from "@/components/ScriptPanel";
import type {
  Idea,
  Job,
  JobStage,
  ResearchBrief,
  ScriptScene,
} from "@/lib/types";

export default function JobPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const { job: liveJob, stages: liveStages, connected } = useJobStream(id);
  const [fallbackJob, setFallbackJob] = useState<Job | null>(null);

  // One-shot fetch in case SSE hasn't connected yet
  useEffect(() => {
    getJob(id).then(setFallbackJob).catch(() => {});
  }, [id]);

  const job = liveJob ?? fallbackJob;

  if (!job) {
    return (
      <main className="max-w-4xl mx-auto p-8">
        <p className="text-muted">Loading…</p>
      </main>
    );
  }

  const stages = liveStages.length > 0 ? liveStages : (job.stages ?? []);

  // Group media by stage for the gallery
  const images = stages.filter((s) => s.name === "image" && s.output_path);
  const clips = stages.filter((s) => s.name === "clip" && s.output_path);
  const audio = stages.filter((s) => s.name === "audio" && s.output_path);

  return (
    <main className="max-w-4xl mx-auto p-8 space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <Link href="/" className="text-xs text-muted hover:text-white">← Library</Link>
          <h1 className="text-lg font-medium mt-2 break-words">{job.prompt}</h1>
          <div className="flex items-center gap-3 mt-2 text-xs text-muted flex-wrap">
            <span>{job.duration}s</span>
            <span>·</span>
            <span>{job.orientation}</span>
            <span>·</span>
            <span className="capitalize">{job.style}</span>
            <span>·</span>
            <span>{(job.language || "en") === "hi" ? "हिन्दी" : "English"}</span>
            <span>·</span>
            <span>created {new Date(job.created_at).toLocaleString()}</span>
            {job.chosen_idea_id && (
              <>
                <span>·</span>
                <span className="text-accent">idea: {job.chosen_idea_id}</span>
              </>
            )}
          </div>
        </div>
        <div className="flex flex-col items-end gap-2">
          <StatusPill status={job.status} />
          <JobActions job={job} />
          {!connected && (job.status === "queued" || job.status === "running") && (
            <span className="text-xs text-amber-400">reconnecting…</span>
          )}
        </div>
      </div>

      {/* Error */}
      {job.error && (
        <div className="rounded-md border border-rose-700 bg-rose-900/20 p-3 text-sm text-rose-200">
          {job.error}
        </div>
      )}

      {/* Idea picker — shown only when paused for the user to pick */}
      {job.status === "awaiting_idea" && (
        <AwaitingIdeaSection jobId={id} />
      )}

      {/* Self-score panel — shown only when paused for accept/retry */}
      {job.status === "awaiting_score" && (
        <AwaitingScoreSection jobId={id} />
      )}

      {/* Stage progress */}
      <section>
        <h2 className="text-sm font-semibold text-muted mb-2">Progress</h2>
        <StageProgress job={job} stages={stages} />
      </section>

      {/* Research Brief — shown once available */}
      <ResearchBriefLoader jobId={id} />

      {/* Scene Script — shown once available */}
      <ScriptLoader jobId={id} />

      {/* Self-score breakdown (always visible once stage succeeded) */}
      <ScoreBreakdownLoader jobId={id} />

      {/* Final video */}
      {job.status === "succeeded" && job.final_path && (
        <section>
          <h2 className="text-sm font-semibold text-muted mb-2">Final video</h2>
          <div className={`rounded-lg border border-border overflow-hidden ${
            job.orientation === "9:16" ? "max-w-xs mx-auto" : "w-full"
          }`}>
            <MediaPreview jobId={job.id} path="final.mp4" />
          </div>
          <p className="text-xs text-muted mt-2">
            🔊 Single continuous video — generated via Veo 3.1 extension
            (no hard cuts between scenes). Voice and SFX generated by Veo natively.
          </p>
        </section>
      )}

      {/* Images gallery */}
      {images.length > 0 && (
        <section>
          <h2 className="text-sm font-semibold text-muted mb-2">Scene images ({images.length})</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {images
              .sort((a, b) => a.stage_index - b.stage_index)
              .map((s) => (
                <div key={`img-${s.stage_index}`} className="rounded-lg border border-border overflow-hidden">
                  <MediaPreview jobId={job.id} path={s.output_path!} />
                </div>
              ))}
          </div>
        </section>
      )}

      {/* Clips gallery — in v2 the clip stage produces ONE continuous mp4,
          so we show a single player labelled "continuous clip" instead of N clips. */}
      {clips.length > 0 && (
        <section>
          <h2 className="text-sm font-semibold text-muted mb-2">Continuous clip</h2>
          <div className={`rounded-lg border border-border overflow-hidden ${
            job.orientation === "9:16" ? "max-w-xs mx-auto" : "w-full"
          }`}>
            <MediaPreview jobId={job.id} path={clips[0].output_path!} />
          </div>
          <p className="text-xs text-muted mt-2">
            Each scene extends the previous clip; the result plays as one
            continuous shot.
          </p>
        </section>
      )}

      {/* Audio narration gallery (only when audio_mode=gemini_tts was used) */}
      {audio.length > 0 && (
        <section>
          <h2 className="text-sm font-semibold text-muted mb-2">Narration audio ({audio.length})</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {audio
              .sort((a, b) => a.stage_index - b.stage_index)
              .map((s) => (
                <div key={`aud-${s.stage_index}`} className="rounded-lg border border-border p-3 bg-panel/40">
                  <p className="text-xs text-muted mb-2">Scene {s.stage_index}</p>
                  <audio
                    controls
                    src={`${process.env.NEXT_PUBLIC_PY_BACKEND ?? "http://127.0.0.1:8765"}/api/media/${job.id}/${s.output_path}`}
                    className="w-full h-8"
                  />
                </div>
              ))}
          </div>
        </section>
      )}
    </main>
  );
}

/** Polls /api/jobs/{id}/ideas and renders the IdeaPicker. */
function AwaitingIdeaSection({ jobId }: { jobId: string }) {
  const [ideas, setIdeas] = useState<{
    ideas: Idea[];
    auto_pick_timeout_sec: number;
  } | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let cancel = false;
    const load = () => {
      getIdeas(jobId)
        .then((d) => {
          if (!cancel) setIdeas(d);
        })
        .catch((e) => {
          if (!cancel) setErr((e as Error).message);
        });
    };
    load();
    const t = setInterval(load, 2000);
    return () => {
      cancel = true;
      clearInterval(t);
    };
  }, [jobId]);

  if (err) {
    return (
      <div className="rounded-md border border-rose-700 bg-rose-900/20 p-3 text-sm text-rose-200">
        Failed to load ideas: {err}
      </div>
    );
  }
  if (!ideas || !ideas.ideas.length) {
    return (
      <div className="rounded-md border border-border bg-panel/40 p-3 text-sm text-muted">
        Loading ideas…
      </div>
    );
  }
  return (
    <IdeaPicker
      jobId={jobId}
      ideas={ideas.ideas}
      autoPickSeconds={ideas.auto_pick_timeout_sec}
    />
  );
}

/** Polls /api/jobs/{id}/score and renders the SelfScorePanel. */
function AwaitingScoreSection({ jobId }: { jobId: string }) {
  const [data, setData] = useState<ScoreResponse | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let cancel = false;
    const load = () => {
      getScore(jobId)
        .then((d) => { if (!cancel) setData(d); })
        .catch((e) => { if (!cancel) setErr((e as Error).message); });
    };
    load();
    const t = setInterval(load, 2000);
    return () => {
      cancel = true;
      clearInterval(t);
    };
  }, [jobId]);

  if (err) {
    return (
      <div className="rounded-md border border-rose-700 bg-rose-900/20 p-3 text-sm text-rose-200">
        Failed to load score: {err}
      </div>
    );
  }
  if (!data) {
    return (
      <div className="rounded-md border border-border bg-panel/40 p-3 text-sm text-muted">
        Loading self-score…
      </div>
    );
  }
  return (
    <SelfScorePanel
      jobId={jobId}
      score={data.score}
      threshold={data.threshold}
      autoAcceptSeconds={data.auto_accept_seconds}
    />
  );
}

/** Lightweight score breakdown shown once score.json exists, regardless of
 *  whether the user is being asked to accept/retry. Mirrors the existing
 *  ResearchBriefLoader / ScriptLoader pattern. */
function ScoreBreakdownLoader({ jobId }: { jobId: string }) {
  const [data, setData] = useState<ScoreResponse | null>(null);
  const [err] = useState<string | null>(null);

  useEffect(() => {
    const load = () => {
      getScore(jobId)
        .then(setData)
        .catch((e) => {
          if (!(e as Error).message.includes("404")) {
            // Non-404 — surface a small note (we don't store err to avoid flicker)
            console.warn("score load error", e);
          }
        });
    };
    load();
    const t = setInterval(load, 5000);
    return () => clearInterval(t);
  }, [jobId]);

  if (!data || !data.score || typeof data.score.total !== "number") return null;
  return (
    <section className="rounded-lg border border-border bg-panel/40 p-4">
      <div className="flex items-center justify-between mb-2">
        <h2 className="text-sm font-semibold text-muted">Self-score</h2>
        <span className="text-xs text-muted">total {data.score.total}/50</span>
      </div>
      <div className="grid grid-cols-5 gap-2 text-center text-[10px]">
        {([
          ["hook", "🎣"],
          ["story", "📖"],
          ["momentum", "⚡"],
          ["emo", "🔗"],
          ["close", "🎬"],
        ] as const).map(([k, e]) => {
          const axis = (
            k === "emo" ? "emotional_linkage" :
            k === "close" ? "closing" :
            k
          ) as keyof typeof data.score;
          const v = (data.score[axis] as number) ?? 0;
          return (
            <div key={k} className="rounded border border-border bg-bg/50 p-2">
              <div className="text-base">{e}</div>
              <div className={`text-lg font-semibold ${v >= 7 ? "text-emerald-300" : v >= 5 ? "text-amber-300" : "text-rose-300"}`}>
                {v}
              </div>
            </div>
          );
        })}
      </div>
      {data.score.one_line_strength && (
        <p className="text-xs text-emerald-300/80 mt-3">
          <strong>Strength:</strong> {data.score.one_line_strength}
        </p>
      )}
      {data.score.one_line_verdict && (
        <p className="text-xs text-amber-300/80 mt-1">
          <strong>To fix:</strong> {data.score.one_line_verdict}
        </p>
      )}
    </section>
  );
}

function ResearchBriefLoader({ jobId }: { jobId: string }) {
  const [brief, setBrief] = useState<ResearchBrief | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    const load = () => {
      getResearchBrief(jobId)
        .then(setBrief)
        .catch((e) => {
          // 404 = not generated yet, that's fine
          if (!(e as Error).message.includes("404")) {
            setErr((e as Error).message);
          }
        });
    };
    load();
    const t = setInterval(load, 3000);
    return () => clearInterval(t);
  }, [jobId]);

  if (!brief && !err) return null;
  if (err) {
    return (
      <div className="rounded-md border border-rose-700 bg-rose-900/20 p-3 text-xs text-rose-200">
        Research brief error: {err}
      </div>
    );
  }
  return <ResearchBriefPanel brief={brief!} />;
}

function ScriptLoader({ jobId }: { jobId: string }) {
  const [data, setData] = useState<{ scenes: ScriptScene[]; chosen_idea: Idea | null } | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    const load = () => {
      getScript(jobId)
        .then(setData)
        .catch((e) => {
          if (!(e as Error).message.includes("404")) {
            setErr((e as Error).message);
          }
        });
    };
    load();
    const t = setInterval(load, 3000);
    return () => clearInterval(t);
  }, [jobId]);

  if (!data && !err) return null;
  if (err) {
    return (
      <div className="rounded-md border border-rose-700 bg-rose-900/20 p-3 text-xs text-rose-200">
        Script error: {err}
      </div>
    );
  }
  return <ScriptPanel scenes={data!.scenes} chosenIdea={data!.chosen_idea} />;
}
